
package examtest;

import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JSeparator;
import javax.swing.JScrollPane;
import java.awt.Dimension;
import java.awt.Component;
import java.awt.Color;
import javax.swing.JPanel;
import java.awt.Font;
import java.awt.LayoutManager;
import javax.swing.LookAndFeel;
import javax.swing.UIManager;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;
import javax.swing.JLabel;
import javax.swing.JFrame;

public class TestResult extends JFrame
{
    Question q;
    QuestionDisplay d;
    JLabel Question1;
    JLabel Question2;
    JLabel Question3;
    JLabel Question4;
    JLabel Question5;
    JLabel Question6;
    JLabel Question7;
    JLabel Question8;
    JLabel Question9;
    JLabel Question10;
    JLabel userAns1;
    JLabel userAns2;
    JLabel userAns3;
    JLabel userAns4;
    JLabel userAns5;
    JLabel userAns6;
    JLabel userAns7;
    JLabel userAns8;
    JLabel userAns9;
    JLabel userAns10;
    JLabel ActualAns1;
    JLabel ActualAns2;
    JLabel ActualAns3;
    JLabel ActualAns4;
    JLabel ActualAns5;
    JLabel ActualAns6;
    JLabel ActualAns7;
    JLabel ActualAns8;
    JLabel ActualAns9;
    JLabel ActualAns10;
    JLabel correct;
    JLabel wrong;
    JLabel Cvalue;
    JLabel Wvalue;
    
    public TestResult() throws Exception {
        this.d = new QuestionDisplay();
        UIManager.setLookAndFeel(new NimbusLookAndFeel());
        final JFrame p = new JFrame("Aptitude Series");
        p.setLayout(null);
        p.setBounds(400, 10, 651, 710);
        final Font f = new Font("lucida calligraphy", 2, 30);
        final JPanel p2 = new JPanel();
        p2.setBounds(0, 0, 650, 50);
        p2.setBackground(Color.GRAY);
        final JLabel head = new JLabel("Result of Test Series ");
        head.setBounds(100, 150, 350, 40);
        head.setForeground(Color.WHITE);
        head.setFont(f);
        p2.add(head);
        p.add(p2);
        final JPanel p3 = new JPanel(null);
        p3.setBackground(Color.WHITE);
        p3.setPreferredSize(new Dimension(600, 1000));
        final Font ft = new Font("Times New Roman", 0, 20);
        final JScrollPane scroll = new JScrollPane(p3, 22, 31);
        scroll.setBounds(0, 50, 638, 580);
        scroll.getVerticalScrollBar().setUnitIncrement(16);
        p.add(scroll);
        final Question q = this.q;
        (this.Question1 = new JLabel(Question.question[0])).setBounds(50, 0, 600, 30);
        this.Question1.setFont(ft);
        p3.add(this.Question1);
        (this.userAns1 = new JLabel("Your Answer : " + QuestionDisplay.Ans1)).setBounds(100, 30, 500, 30);
        this.userAns1.setFont(ft);
        p3.add(this.userAns1);
        final StringBuilder append = new StringBuilder().append("Actual Answer : ");
        final Question q2 = this.q;
        (this.ActualAns1 = new JLabel(append.append(Question.option1[0]).toString())).setBounds(100, 60, 500, 30);
        this.ActualAns1.setFont(ft);
        p3.add(this.ActualAns1);
        final JSeparator sp1 = new JSeparator(0);
        sp1.setBounds(0, 90, 650, 30);
        p3.add(sp1);
        final Question q3 = this.q;
        (this.Question2 = new JLabel(Question.question[1])).setBounds(50, 100, 600, 30);
        this.Question2.setFont(ft);
        p3.add(this.Question2);
        (this.userAns2 = new JLabel("Your Answer : " + QuestionDisplay.Ans2)).setBounds(100, 130, 500, 30);
        this.userAns2.setFont(ft);
        p3.add(this.userAns2);
        final StringBuilder append2 = new StringBuilder().append("Actual Answer : ");
        final Question q4 = this.q;
        (this.ActualAns2 = new JLabel(append2.append(Question.option2[3]).toString())).setBounds(100, 160, 500, 30);
        this.ActualAns2.setFont(ft);
        p3.add(this.ActualAns2);
        final JSeparator sp2 = new JSeparator(0);
        sp2.setBounds(0, 190, 650, 30);
        p3.add(sp2);
        final Question q5 = this.q;
        (this.Question3 = new JLabel(Question.question[2])).setBounds(50, 200, 600, 30);
        this.Question3.setFont(ft);
        p3.add(this.Question3);
        (this.userAns3 = new JLabel("Your Answer : " + QuestionDisplay.Ans3)).setBounds(100, 230, 500, 30);
        this.userAns3.setFont(ft);
        p3.add(this.userAns3);
        final StringBuilder append3 = new StringBuilder().append("Actual Answer : ");
        final Question q6 = this.q;
        (this.ActualAns3 = new JLabel(append3.append(Question.option3[1]).toString())).setBounds(100, 260, 500, 30);
        this.ActualAns3.setFont(ft);
        p3.add(this.ActualAns3);
        final JSeparator sp3 = new JSeparator(0);
        sp3.setBounds(0, 290, 650, 30);
        p3.add(sp3);
        final Question q7 = this.q;
        (this.Question4 = new JLabel(Question.question[3])).setBounds(50, 300, 600, 30);
        this.Question4.setFont(ft);
        p3.add(this.Question4);
        (this.userAns4 = new JLabel("Your Answer : " + QuestionDisplay.Ans4)).setBounds(100, 330, 500, 30);
        this.userAns4.setFont(ft);
        p3.add(this.userAns4);
        final StringBuilder append4 = new StringBuilder().append("Actual Answer : ");
        final Question q8 = this.q;
        (this.ActualAns4 = new JLabel(append4.append(Question.option4[0]).toString())).setBounds(100, 360, 500, 30);
        this.ActualAns4.setFont(ft);
        p3.add(this.ActualAns4);
        final JSeparator sp4 = new JSeparator(0);
        sp4.setBounds(0, 390, 650, 30);
        p3.add(sp4);
        final Question q9 = this.q;
        (this.Question5 = new JLabel(Question.question[4])).setBounds(50, 400, 600, 30);
        this.Question5.setFont(ft);
        p3.add(this.Question5);
        (this.userAns5 = new JLabel("Your Answer : " + QuestionDisplay.Ans5)).setBounds(100, 430, 500, 30);
        this.userAns5.setFont(ft);
        p3.add(this.userAns5);
        final StringBuilder append5 = new StringBuilder().append("Actual Answer : ");
        final Question q10 = this.q;
        (this.ActualAns5 = new JLabel(append5.append(Question.option5[3]).toString())).setBounds(100, 460, 500, 30);
        this.ActualAns5.setFont(ft);
        p3.add(this.ActualAns5);
        final JSeparator sp5 = new JSeparator(0);
        sp5.setBounds(0, 490, 650, 30);
        p3.add(sp5);
        final Question q11 = this.q;
        (this.Question6 = new JLabel(Question.question[5])).setBounds(50, 500, 600, 30);
        this.Question6.setFont(ft);
        p3.add(this.Question6);
        (this.userAns6 = new JLabel("Your Answer : " + QuestionDisplay.Ans6)).setBounds(100, 530, 500, 30);
        this.userAns6.setFont(ft);
        p3.add(this.userAns6);
        final StringBuilder append6 = new StringBuilder().append("Actual Answer : ");
        final Question q12 = this.q;
        (this.ActualAns6 = new JLabel(append6.append(Question.option6[3]).toString())).setBounds(100, 560, 500, 30);
        this.ActualAns6.setFont(ft);
        p3.add(this.ActualAns6);
        final JSeparator sp6 = new JSeparator(0);
        sp6.setBounds(0, 590, 650, 30);
        p3.add(sp6);
        final Question q13 = this.q;
        (this.Question7 = new JLabel(Question.question[6])).setBounds(50, 600, 600, 30);
        this.Question7.setFont(ft);
        p3.add(this.Question7);
        (this.userAns7 = new JLabel("Your Answer : " + QuestionDisplay.Ans7)).setBounds(100, 630, 500, 30);
        this.userAns7.setFont(ft);
        p3.add(this.userAns7);
        final StringBuilder append7 = new StringBuilder().append("Actual Answer : ");
        final Question q14 = this.q;
        (this.ActualAns7 = new JLabel(append7.append(Question.option7[2]).toString())).setBounds(100, 660, 500, 30);
        this.ActualAns7.setFont(ft);
        p3.add(this.ActualAns7);
        final JSeparator sp7 = new JSeparator(0);
        sp7.setBounds(0, 690, 650, 30);
        p3.add(sp7);
        final Question q15 = this.q;
        (this.Question8 = new JLabel(Question.question[7])).setBounds(50, 700, 600, 30);
        this.Question8.setFont(ft);
        p3.add(this.Question8);
        (this.userAns8 = new JLabel("Your Answer : " + QuestionDisplay.Ans8)).setBounds(100, 730, 500, 30);
        this.userAns8.setFont(ft);
        p3.add(this.userAns8);
        final StringBuilder append8 = new StringBuilder().append("Actual Answer : ");
        final Question q16 = this.q;
        (this.ActualAns8 = new JLabel(append8.append(Question.option8[0]).toString())).setBounds(100, 760, 500, 30);
        this.ActualAns8.setFont(ft);
        p3.add(this.ActualAns8);
        final JSeparator sp8 = new JSeparator(0);
        sp8.setBounds(0, 790, 650, 30);
        p3.add(sp8);
        final Question q17 = this.q;
        (this.Question9 = new JLabel(Question.question[8])).setBounds(50, 800, 600, 30);
        this.Question9.setFont(ft);
        p3.add(this.Question9);
        (this.userAns9 = new JLabel("Your Answer : " + QuestionDisplay.Ans9)).setBounds(100, 830, 500, 30);
        this.userAns9.setFont(ft);
        p3.add(this.userAns9);
        final StringBuilder append9 = new StringBuilder().append("Actual Answer : ");
        final Question q18 = this.q;
        (this.ActualAns9 = new JLabel(append9.append(Question.option9[3]).toString())).setBounds(100, 860, 500, 30);
        this.ActualAns9.setFont(ft);
        p3.add(this.ActualAns9);
        final JSeparator sp9 = new JSeparator(0);
        sp9.setBounds(0, 890, 650, 30);
        p3.add(sp9);
        final Question q19 = this.q;
        (this.Question10 = new JLabel(Question.question[9])).setBounds(50, 900, 600, 30);
        this.Question10.setFont(ft);
        p3.add(this.Question10);
        (this.userAns10 = new JLabel("Your Answer : " + QuestionDisplay.Ans10)).setBounds(100, 930, 500, 30);
        this.userAns10.setFont(ft);
        p3.add(this.userAns10);
        final StringBuilder append10 = new StringBuilder().append("Actual Answer : ");
        final Question q20 = this.q;
        (this.ActualAns10 = new JLabel(append10.append(Question.option10[3]).toString())).setBounds(100, 960, 500, 30);
        this.ActualAns10.setFont(ft);
        p3.add(this.ActualAns10);
        final JSeparator sp10 = new JSeparator(0);
        sp10.setBounds(0, 990, 650, 30);
        p3.add(sp10);
        p3.repaint();
        final JPanel p4 = new JPanel();
        p4.setLayout(null);
        p4.setBounds(0, 630, 650, 40);
        p4.setBackground(Color.LIGHT_GRAY);
        (this.correct = new JLabel("Correct Answer : ")).setBounds(20, 10, 150, 30);
        this.correct.setFont(ft);
        this.correct.setBackground(Color.red);
        p4.add(this.correct);
        (this.Cvalue = new JLabel(String.valueOf(this.d.getCorrect()))).setBounds(170, 10, 50, 30);
        this.Cvalue.setBackground(Color.BLUE);
        this.Cvalue.setFont(ft);
        p4.add(this.Cvalue);
        (this.wrong = new JLabel("Wrong Answer : ")).setBounds(220, 10, 150, 30);
        this.wrong.setFont(ft);
        p4.add(this.wrong);
        (this.Wvalue = new JLabel(String.valueOf(this.d.getWrong()))).setBounds(350, 10, 50, 30);
        this.Wvalue.setFont(ft);
        p4.add(this.Wvalue);
        final JButton exit = new JButton("Exit");
        exit.setBounds(500, 5, 100, 35);
        exit.setFont(ft);
        p4.add(exit);
        exit.addActionListener(e -> System.exit(0));
        p.add(p4);
        p.setVisible(true);
    }
}